nelmio_api_doc:
    documentation:
        info:
            title: Calculation API
            description: Simple Calculation API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/add
            - ^/sub
            - ^/mul
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
